# For a repository named AhmedHanafy725/test_zeroci
jobs:
  - name: building bcdb
    prerequisites:
      image_name: ubuntu:20.04

    install: |
      apt-get update
      apt-get install -y git tmux build-essential
      cd /zeroci/code/
      git clone https://github.com/threefoldtech/0-db.git
      cd 0-db
      make
      tmux new -d -s zdb "/zeroci/code/0-db/bin/zdb --mode seq"
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      cd /zeroci/code
      git clone https://github.com/threefoldtech/bcdb.git
      cd bcdb 
      make 
    script:
      - name: Test BCDB Bin
        cmd: |
          bcdb --help
 
