# For a repository named AhmedHanafy725/test_zeroci
jobs:
  - name: Generate Publishing Tool Bin
    prerequisites:
      image_name: crystallang/crystal:0.35.1-alpine

    install: |
      apk update
      apk add libssh2-static libssh2 libssh2-dev
      apk add git
      cd /zeroci/code/vcs_repos/
      git clone https://github.com/threefoldfoundation/publishingtools.git
      cd publishingtools
      shards build --static --link-flags "$(pkg-config libxml-2.0 --libs --static)" --link-flags "$(pkg-config libssh2 --libs --static)"

    script:
      - name: Test Bin
        cmd: |
          /zeroci/code/vcs_repos/publishingtools/bin/tfweb -v

    bin_path: /zeroci/code/vcs_repos/publishingtools/bin/tfweb

  - name: Use Publishing Tool Bin
    prerequisites:
      image_name: ubuntu:18.04

    install: |
      apt-get update

    script:
      - name: Test Bin
        cmd: |
          /opt/bin/tfweb -v 


