# For a repository named AhmedHanafy725/test_zeroci
run_on:

jobs:
  - name: Generate Bin
    prerequisites:
      image_name: ubuntu:18.04
      shell_bin: /bin/sh

    install: |
      apt-get update
      apt-get install -y python3.6 python3-pip
      pip3 install nose

    script:
      - name: Tests Bin
        cmd: |
          nosetests --help
      - name: Smiple Tests With Nosetest
        cmd: |
          cd /zeroci/code/vcs_repos/AhmedHanafy725/test_zeroci
          nosetests -v testcase.py --with-xunit --xunit-file=/test.xml --xunit-testsuite-name=Simple_nosetest

    bin_path: /usr/local/bin/nosetests

  - name: Use Bin
    prerequisites:
      image_name: ubuntu:18.04
      shell_bin: /bin/sh

    install: |
      apt-get update
      apt-get install -y python3.6 python3-pip

    script:
      - name: Test nosetests Bin
        cmd: |
          cd /zeroci/code/vcs_repos/AhmedHanafy725/test_zeroci
          /zeroci/bin/nosetests -v testcase.py --with-xunit --xunit-file=/test.xml --xunit-testsuite-name=Simple_nosetest

