# For a repository named AhmedHanafy725/test_zeroci
jobs:
  - name: Neph
    prerequisites:
      image_name: ubuntu

    install: |
      apt-get update

    script:
      - name: Test neph
        type: neph
        working_dir: /zeroci/code/vcs_repos/AhmedHanafy725/test_zeroci
        yaml_path: /zeroci/code/vcs_repos/AhmedHanafy725/test_zeroci/neph.yaml

