# For a repository named AhmedHanafy725/test_zeroci
jobs:
  - name: Generate Bin
    prerequisites:
      image_name: ubuntu:18.04
      shell_bin: /bin/sh

    install: |
      apt-get update
      apt-get install -y python3.6 python3-pip
      pip3 install pytest

    script:
      - name: Tests Bin
        cmd: |
          nosetests --help
      - name: Smiple Tests With Pytest
        cmd: |
          cd /opt/code/vcs_repos/AhmedHanafy725/test_zeroci
          pytest -v testcase.py --with-xunit --xunit-file=/test.xml --xunit-testsuite-name=Simple_nosetest

    bin_path: /usr/local/bin/pytest

  - name: Use Bin
    prerequisites:
      image_name: ubuntu:18.04
      shell_bin: /bin/sh

    install: |
      apt-get update
      apt-get install -y python3.6 python3-pip
      sleep 200

    script:
      - name: Test pytest Bin
        cmd: |
          cd /opt/code/vcs_repos/AhmedHanafy725/test_zeroci
          /usr/local/bin/pytest -v testcase.py --junitxml=/test.xml -o junit_suite_name=Simple_pytest
