# For a repository named AhmedHanafy725/test_zeroci

jobs:
  - name: Building BCDB
    prerequisites:
      image_name: ubuntu:20.04

    install: |
      # Install dependencies
      apt-get update
      apt-get install -y git tmux build-essential curl wget musl musl-tools
      
      # Install ZDB
      cd /zeroci/code/
      git clone https://github.com/threefoldtech/0-db.git
      cd 0-db
      make
      cp /zeroci/code/0-db/bin/zdb /usr/local/bin/
      
      # Install rust
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      cp ~/.cargo/bin/* /usr/local/bin/

      # Install BCDB
      cd /zeroci/code
      git clone https://github.com/threefoldtech/bcdb.git
      cd bcdb 
      make

    script:
      - name: Start BCDB instance 1
        cmd: |
          mkdir -p /root/test_bcdb/instance1
          cd /root/test_bcdb/instance1
          echo "{\"id\": $tid1, \"host\": \"http://0.0.0.0:50051\", \"pubkey\": \"$pubkey1\"}" > /root/test_bcdb/peers.json
          echo "{\"id\": $tid2, \"host\": \"http://0.0.0.0:50052\", \"pubkey\": \"$pubkey2\"}" > /root/test_bcdb/peers.json
          tmux new-session -d -s instance1
          tmux new-window -d -t instance1 -n zdb "zdb --mode seq --port 9900 --data /root/test_bcdb/instance1 --index /root/test_bcdb/instance1"
          tmux new-window -d -t instance1 -n bcdb "bcdb --threebot-id $tid1 --seed \"$words1\" --peers-file /root/test_bcdb/peers.json --seed-file user.seed --rest /root/test_bcdb/instance1/bcdb.sock --zdb 9900 --grpc 0.0.0.0:50051 --meta ~/.bcdb-meta1"
      - name: Start BCDB instance 2
        cmd: |
          mkdir -p /root/test_bcdb/instance2
          cd /root/test_bcdb/instance2
          tmux new-session -d -s instance2
          tmux new-window -d -t instance2 -n zdb "zdb --mode seq --port 9901 --data /root/test_bcdb/instance2 --index /root/test_bcdb/instance2"
          tmux new-window -d -t instance2 -n bcdb "bcdb --threebot-id $tid2 --seed \"$words2\" --peers-file /root/test_bcdb/peers.json --seed-file user.seed --rest /root/test_bcdb/instance2/bcdb.sock --zdb 9901 --grpc 0.0.0.0:50052 --meta ~/.bcdb-meta2"
          sleep 600
    bin_path: /zeroci/code/bcdb/target/x86_64-unknown-linux-musl/release/bcdb
