# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master , win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: try pwd
      run: |
        pwd
    - name: Install dependencies
      run: |
        $script = New-Object Net.WebClient
        $script | Get-Member
        $script.DownloadString("https://chocolatey.org/install.ps1")
        iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
    - name: clone
      run: |
        git clone https://github.com/threefoldtech/jumpscaleX_core.git
        chdir ".\jumpscaleX_core\install\"
    - name: install packages
      run: |
        choco install -y python --version=3.7.2
        choco install -y docker-desktop docker git
    - name: generate ssh key
      run: |
        docker ps
        ssh-keygen -t ecdsa -b 521 -N '""' -f "$HOME/.ssh/id_ecdsa"
        
    - name: install jsx
      run: |
        pwd;
        chdir ".\jumpscaleX_core\install\";
        pwd;
        package.bat
        ./dist/3sdk.exe container install identity=test.test secret=test
