# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, development-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew cask install docker
        brew install upx
        brew install patchelf
        pip3 install pyinstaller
        pip3 install jedi
        pip3 install ptpython==2.0.4
        pip3 install pudb
    - name: Lint with black
      run: |
        pip3 install black
    - name: install jsx 
      run: |
        git clone https://github.com/threefoldtech/jumpscaleX_core --branch development
        cd jumpscaleX_core/install
        ./package.sh
        cd dist
        ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa -q -P ""
        eval `ssh-agent`
        ssh-add
        killall Docker && open /Applications/Docker.app
        ./3sdk container install identity=test.test secret=test
        
