# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master , win ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        $script = New-Object Net.WebClient
        $script | Get-Member
        $script.DownloadString("https://chocolatey.org/install.ps1")
        iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
        choco install -y python --version=3.7.2
        choco install -y git docker-desktop docker
        ssh-keygen -t ecdsa -b 521
    - name: install jsx 
      run: |
        git clone https://github.com/threefoldtech/jumpscaleX_core --branch development
        cd jumpscaleX_core/install
        package.bat
        cd dist
        3sdk.exe container install identity=test.test secret=test
