# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master , win ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.7' 
        architecture: 'x64'
    - name: Install dependencies
      run: |
        $script = New-Object Net.WebClient
        $script | Get-Member
        $script.DownloadString("https://chocolatey.org/install.ps1")
        iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
    - name: clone
      run: git clone https://github.com/threefoldtech/jumpscaleX_core.git
    - name: install docker
      run: |
        choco install -y docker-desktop docker
        docker ps
    - name: enable docker
      run: |
        set LCOW_SUPPORTED=1
    - name: generate ssh key
      run: |
        ssh-keygen -t ecdsa -b 521 -N '""' -f "$HOME/.ssh/id_ecdsa"
    - name: filesystem
      run: |
        chdir ".\jumpscaleX_core\install\"
        pwd
    - name: install jsx
      run: |
        chdir ".\jumpscaleX_core\install\"
        ./package.bat
        ./dist/3sdk.exe container install identity=test.test secret=test
